<?php

function shift_cipher_menu() {
  $items['cipher'] = array(
    'title' => 'Shift Cipher',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('shift_cipher_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['encrypted'] = array(
    'title' => 'Phrase Encrypted',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
    'page callback' => 'shift_cipher_encrypted',
  );
  return $items;
}

function shift_cipher_form() {
  $form['shift_value'] = array(
    '#title' => 'Shift Value',
    '#type' => 'textfield',
    '#description' => t('Shift value'),
  );

  $form['direction'] = array(
    '#title' => 'Direction',
    '#type' => 'select',
    '#options' => array(
      0 => t('forward/right'),
      1 => t('backward/left'),
    ),
    '#description' => t('The direction within the alphabet that the cipher will shift, i.e., "forward/right" would be traversing the alphabet how it is read normally. If the letter was "E" with a shift of "3" it would become "H", and "B" with the same shift value of "3" but opposite direction  "backward/left"'),
  );

  $form['phrase'] = array(
    '#title' => 'Phrase',
    '#type' => 'textarea',
    '#description' => t('The phrase to cipher shift'),
    '#value' => 'Totally, totally, totally, I will have your money whenever I get a job',
  );

  $form['submit'] = array(
          '#type' => 'submit',
          '#value' => 'Encrypt',
      );

  return $form;
}

function shift_cipher_form_submit($form, &$form_state) {
  $shift_value = $form_state['values']['shift_value'];
  $direction = $form_state['values']['direction'];
  $phrase = strtolower($form_state['values']['phrase']);
  $split_phrase = str_split($phrase);
  $character_pattern = '/\w/';
  $new_char = 0;
  if ($shift_value > 26) {
    $quotient = floor($shift_value / 26);
    $shift_value -= (26 * $quotient);
    $_SESSION['shift_value'] = $quotient;
  }

  foreach($split_phrase as &$char) {
    if (preg_match($character_pattern, $char)) {
      $ascii_value = ord($char);
      if ($direction) {
        $new_char = ($ascii_value - $shift_value);
        if ($new_char < 97) {
          $new_char += 26;
        }
        $char = chr($new_char);
      } else {
        $new_char = ($ascii_value + $shift_value);
        if ($new_char > 122) {
          $new_char -= 26;
        }
        $char = chr($new_char);
      }
    }
  }

  $_SESSION['split_phrase'] = implode($split_phrase);
  $_SESSION['encrypted_phrase'] = $phrase;
  $form_state['redirect'] = 'encrypted';
}

function shift_cipher_encrypted() {

  return var_dump($_SESSION['split_phrase']) . "<br>" . $_SESSION['encrypted_phrase'] . '<br>' . $_SESSION['shift_value'];
}
